services:
  server:
    image: evancestnick/spice-stream-backend
    container_name: spice-stream-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
